sudo: required
language: node_js
node_js:
- node
before_script:
- npm --silent run sticky:test:sonar -- -Dsonar.organization=bikecoders -Dsonar.host.url=https://sonarcloud.io
  -Dsonar.login=$SONARCLOUD_TOKEN
script:
- npm run sticky:build-prod
before_deploy:
- npm run sticky:publish:copy-files
- cd projects/sticky-directive
after_deploy:
- cd ../..
- yarn upgrade ngx-sticky --force && yarn list ngx-sticky && npm run deploy-gh-pages
deploy:
  provider: npm
  email: bikecoders@gmail.com
  skip_cleanup: true
  api_key:
    secure: Mf7ZB2RoS0edx1bKEms/kRIsujIXld4JZLGoap34nGOlv+7001VU418N820qglLHhTtAQhSV9f9ijP5DRvm+qsTJBc9cWRuU6TxHHifwvx0PUpWsR5vXQf7k4Lr8Yno3afRDpO54Kdol4E7auBn/rLB4bbik5f4gfnFvZJ6lDJEOI8E7HG3bQsf6hVUW3/45ybiJF16XhJtgKY07OEiEEZfMbbe1crz3O3yjQKYFlRJasGy/iOY1bhBvS+aUCCoYLMEpp757VbiyLgaWkObau8oJPGCZ5OwseulrYOiqe2Bi36FREbxiyW3HmyXhCrTogwuHvXOWJCaPSJYZz2piu6LvLWRiMz4ubN/T5OrVN3fSPB9/S/r8ns1S7DAiNegzszzQr32k7EgMyOh9vU0XTmb0F55E0VK+YjW0Ck3mbsh/1VgBIaQ4ID6lxKPgLpkGJQiA8PYSx7eyRq7iiKFvJVBNP6O55GZbzTGjHR5Uh3ShOn8FiV7FuuHIGtgiuHRpueqT5Y2ySgxCxrejTs16eyHpZ90oFYphdpnOUKC9kBZQkyAW6zeYU0jPiNI+F/83Q0xm41tkHwRW4RmG0p+zypkepXjx4a9SiicKTqGXjr9cSy5ytIGWDOREju1XrUmXeKHrCdi7YK6MY2f6UUcJbsfoGNolTVLDhR/XAchwv18=
  on:
    tags: true
    repo: bikecoders/ngx-sticky
